import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to  <br/> <a href="">Koding Academy</a>
        </h1>

        <p className={styles.description}>
          Coming Soon..
        </p>

        <div className={styles.grid}>
          <a href="https://instagram.com/kodingacademy_com?igshid=YmMyMTA2M2Y=" target="_blank" rel="noreferrer" className={styles.card}>
            <h2>Visit Instagram</h2>
            <p>Our Instagram Account Here.</p>
          </a>

          <a href="https://www.youtube.com/channel/UC_gpERDENt9jnAOIgAi0SqQ" target="_blank" rel="noreferrer" className={styles.card}>
            <h2>Visit Youtube</h2>
            <p>Our Youtube Channel here.</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
